import * as fs from 'fs'
import * as path from 'path'
import chalk from 'chalk'
import ora from 'ora'
import { createSupabaseClient } from '@tages/shared'
import { getProjectsDir } from '../config/paths.js'

interface ExportOptions {
  project?: string
  output?: string
  format?: string
}

export async function exportCommand(options: ExportOptions) {
  const config = loadProjectConfig(options.project)
  if (!config) {
    console.error(chalk.red('No project configured. Run `tages init` first.'))
    process.exit(1)
  }

  if (!config.supabaseUrl || !config.supabaseAnonKey) {
    console.error(chalk.red('Export requires cloud connection.'))
    process.exit(1)
  }

  const spinner = ora('Loading memories...').start()
  const supabase = createSupabaseClient(config.supabaseUrl, config.supabaseAnonKey)

  const { data: memories } = await supabase
    .from('memories')
    .select('*')
    .eq('project_id', config.projectId)
    .order('type')
    .order('updated_at', { ascending: false })

  if (!memories || memories.length === 0) {
    spinner.info('No memories to export.')
    return
  }

  const format = options.format || 'claude-md'

  let content: string
  let filename: string

  switch (format) {
    case 'claude-md':
      content = exportAsCLAUDEmd(memories, config.slug)
      filename = 'CLAUDE.md'
      break
    case 'architecture-md':
      content = exportAsArchitectureMd(memories, config.slug)
      filename = 'ARCHITECTURE.md'
      break
    case 'json':
      content = JSON.stringify(memories, null, 2)
      filename = 'tages-memories.json'
      break
    default:
      content = exportAsCLAUDEmd(memories, config.slug)
      filename = 'CLAUDE.md'
  }

  const outputPath = options.output || path.join(process.cwd(), filename)
  fs.writeFileSync(outputPath, content)

  spinner.succeed(`Exported ${memories.length} memories to ${outputPath}`)
}

function exportAsCLAUDEmd(memories: Record<string, unknown>[], slug: string): string {
  const grouped: Record<string, Record<string, unknown>[]> = {}
  for (const m of memories) {
    const type = m.type as string
    if (!grouped[type]) grouped[type] = []
    grouped[type].push(m)
  }

  const sections: string[] = []
  sections.push(`# ${slug} — Project Configuration`)
  sections.push('')
  sections.push(`> Generated by Tages from ${memories.length} memories.`)
  sections.push(`> Last exported: ${new Date().toISOString().split('T')[0]}`)
  sections.push('')

  if (grouped.convention) {
    sections.push('## Conventions')
    sections.push('')
    for (const m of grouped.convention) {
      sections.push(`### ${m.key}`)
      sections.push(m.value as string)
      if ((m.file_paths as string[])?.length) {
        sections.push(`\n_Files: ${(m.file_paths as string[]).join(', ')}_`)
      }
      sections.push('')
    }
  }

  if (grouped.architecture) {
    sections.push('## Architecture')
    sections.push('')
    for (const m of grouped.architecture) {
      sections.push(`### ${m.key}`)
      sections.push(m.value as string)
      if ((m.file_paths as string[])?.length) {
        sections.push(`\n_Files: ${(m.file_paths as string[]).join(', ')}_`)
      }
      sections.push('')
    }
  }

  if (grouped.decision) {
    sections.push('## Decisions')
    sections.push('')
    for (const m of grouped.decision) {
      sections.push(`### ${m.key}`)
      sections.push(m.value as string)
      sections.push('')
    }
  }

  if (grouped.pattern) {
    sections.push('## Patterns')
    sections.push('')
    for (const m of grouped.pattern) {
      sections.push(`### ${m.key}`)
      sections.push(m.value as string)
      sections.push('')
    }
  }

  if (grouped.lesson) {
    sections.push('## Lessons')
    sections.push('')
    for (const m of grouped.lesson) {
      sections.push(`- **${m.key}**: ${m.value}`)
    }
    sections.push('')
  }

  if (grouped.entity) {
    sections.push('## Entities')
    sections.push('')
    for (const m of grouped.entity) {
      sections.push(`- **${m.key}**: ${m.value}`)
    }
    sections.push('')
  }

  return sections.join('\n')
}

function exportAsArchitectureMd(memories: Record<string, unknown>[], slug: string): string {
  const arch = memories.filter(m => m.type === 'architecture')
  const sections: string[] = []

  sections.push(`# ${slug} — Architecture`)
  sections.push('')
  sections.push(`> Generated by Tages from ${arch.length} architecture memories.`)
  sections.push('')

  for (const m of arch) {
    sections.push(`## ${m.key}`)
    sections.push('')
    sections.push(m.value as string)
    if ((m.file_paths as string[])?.length) {
      sections.push(`\n**Files:** ${(m.file_paths as string[]).join(', ')}`)
    }
    sections.push('')
  }

  return sections.join('\n')
}

function loadProjectConfig(slug?: string) {
  const dir = getProjectsDir()
  if (!fs.existsSync(dir)) return null
  if (slug) {
    const p = `${dir}/${slug}.json`
    if (!fs.existsSync(p)) return null
    return JSON.parse(fs.readFileSync(p, 'utf-8'))
  }
  const files = fs.readdirSync(dir).filter((f: string) => f.endsWith('.json'))
  if (files.length === 0) return null
  return JSON.parse(fs.readFileSync(`${dir}/${files[0]}`, 'utf-8'))
}
