import { Button, Section, SectionHead } from './ui'

const PLANS = [
  {
    name: 'Free',
    price: '$0',
    period: '',
    description: 'For solo developers. Works offline.',
    features: [
      '1 project (cloud sync)',
      '10,000 memories',
      '20 core MCP tools',
      'SQLite local-first (unlimited offline projects)',
      'tages brief generation',
      'Community support',
    ],
    cta: 'Get started',
    href: '/auth/login',
    highlighted: true,
  },
  {
    name: 'Pro',
    price: '$14',
    period: '/month',
    description: 'For professional developers.',
    features: [
      'All 56 MCP tools',
      'Up to 10 projects',
      '50,000 memories',
      'Supabase cloud sync',
      'Fuzzy + semantic search',
      'Quality scoring + analytics',
    ],
    cta: 'Get Pro',
    href: '/app/upgrade',
    highlighted: false,
  },
  {
    name: 'Team',
    price: '$19',
    period: '/seat/mo',
    description: 'For shared codebases. 1–20 seats.',
    features: [
      'Everything in Pro',
      '100,000 memories per project',
      'Team memory federation',
      'RBAC + audit logging',
      'Centralized seat billing',
      'Priority support',
    ],
    cta: 'Get Team',
    href: '/app/upgrade',
    highlighted: false,
  },
  {
    name: 'Self-hosted',
    price: '$0',
    period: 'forever',
    description: 'Your infrastructure, your data.',
    features: [
      'Full feature parity',
      'No memory limits',
      'AES-256 encryption',
      'Air-gapped compatible',
      'MIT license',
      'Community support',
    ],
    cta: 'Read the guide',
    href: '/docs/self-hosting',
    highlighted: false,
  },
]

function Check() {
  return (
    <svg
      aria-hidden
      viewBox="0 0 16 16"
      fill="none"
      strokeWidth="1.5"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      className="mt-[0.35rem] h-3.5 w-3.5 shrink-0 text-signal-600"
    >
      <path d="M3 8.5 6.2 11.7 13 4.9" />
    </svg>
  )
}

export function Pricing() {
  return (
    <Section id="pricing">
      <SectionHead
        title="Pricing"
        lead="Start free. The local-first mode keeps working whether or not you ever sign in."
      />

      <div className="mt-14 grid gap-px overflow-hidden rounded-card border border-line bg-line-strong sm:grid-cols-2 lg:grid-cols-4">
        {PLANS.map((plan) => (
          <div
            key={plan.name}
            className={`flex flex-col p-6 ${plan.highlighted ? 'bg-paper-sunken' : 'bg-paper-raised'}`}
          >
            <h3 className="text-heading text-ink">{plan.name}</h3>

            <p className="mt-3 flex items-baseline gap-1" data-numeric>
              <span className="text-title text-ink">{plan.price}</span>
              {plan.period ? (
                <span className="text-label text-ink-muted">{plan.period}</span>
              ) : null}
            </p>

            <p className="mt-2.5 text-label text-ink-soft">{plan.description}</p>

            <ul className="mt-6 flex-1 space-y-2.5">
              {plan.features.map((f) => (
                <li key={f} className="flex gap-2.5 text-label text-ink-soft">
                  <Check />
                  <span>{f}</span>
                </li>
              ))}
            </ul>

            <div className="mt-7">
              <Button
                href={plan.href}
                variant={plan.highlighted ? 'primary' : 'secondary'}
                className="w-full"
              >
                {plan.cta}
              </Button>
            </div>
          </div>
        ))}
      </div>

      <p className="mt-6 text-label text-ink-muted">
        Questions about Team billing?{' '}
        <a
          href="mailto:support@tages.ai"
          className="text-ink underline decoration-line-strong hover:decoration-ink-muted"
        >
          support@tages.ai
        </a>
      </p>
    </Section>
  )
}

/*
  The previous version of this file also exported a PricingComparison table
  asserting competitor pricing, tool counts, and capabilities for Mem0, Zep,
  Supermemory, and MemPalace, carrying an "as of Apr 2026" disclaimer. Those are
  third-party facts this project cannot verify and that go stale silently, so
  the table is gone rather than restyled. Two FAQ entries that argued against
  named competitors went with it.
*/

const FAQ = [
  {
    q: 'Do I need to install anything for semantic search?',
    a: 'No. Embeddings are generated by an endpoint Tages runs, so there is no local model, no API key, and nothing to configure. If that endpoint is ever unreachable, recall falls back to literal text matching rather than failing.',
  },
  {
    q: 'What happens if I exceed my memory limit?',
    a: 'On Free, older memories are archived when you hit the cap. On Pro, you get a warning at 80% and can upgrade or clean up. Team includes 100,000 memories per project.',
  },
  {
    q: 'How does a teammate join a project I already created?',
    a: 'You invite them by email from the project settings page, which also shows the project ID. They run tages link --project-id from their own repository. Membership is enforced in the database, so a non-member gets nothing rather than a filtered view.',
  },
  {
    q: 'What does tages brief do?',
    a: 'It generates a cached context file you can inject into a system prompt, keeping project knowledge pinned at the top of every turn instead of relying on a tool call to fetch it.',
  },
  {
    q: 'Is self-hosted really free?',
    a: 'Yes. MIT license, no usage limits, no phone-home. Bring your own Supabase instance and you have full Tages at no cost.',
  },
]

export function PricingFAQ() {
  return (
    <Section>
      <SectionHead title="Questions" />
      <dl className="mt-12 grid gap-x-16 gap-y-9 sm:grid-cols-2">
        {FAQ.map((item) => (
          <div key={item.q}>
            <dt className="text-heading text-ink">{item.q}</dt>
            <dd className="mt-2.5 text-ink-soft">{item.a}</dd>
          </div>
        ))}
      </dl>
    </Section>
  )
}
