import { CodePanel, Section, SectionHead } from './ui'

export function Search() {
  return (
    <Section tight>
      <div className="grid gap-12 lg:grid-cols-[1fr_1.05fr] lg:gap-16 lg:items-start">
        <div className="min-w-0">
          <SectionHead
            title="Semantic search that needs nothing running on your machine."
            lead="Ask in your own words. Embeddings are generated by an endpoint Tages runs, so there is no local model to install, no key to provision, and nothing to configure."
          />

          <div className="mt-8 space-y-5 measure text-ink-soft">
            <p>
              That is a correctness property, not just a convenience. When each developer
              embeds locally, one teammate running a different model quietly writes vectors
              into the shared index that cannot be compared to anyone else&apos;s. Similarity
              across two models is meaningless, so the results come back confident and wrong.
            </p>
            <p>
              Running it in one place makes the index uniform by construction rather than by
              everyone remembering to configure the same thing. If the endpoint is ever
              unreachable, recall falls back to literal text matching. It never silently
              substitutes a different model.
            </p>
          </div>
        </div>

        <div className="min-w-0 lg:pt-2">
          <CodePanel
            lines={[
              { text: '$ tages recall "how do we handle database migrations safely"', tone: 'accent' },
              { text: '' },
              { text: '  convention    supabase-cli-skips-letter-suffix-migrations' },
              { text: '  operational   sync-interval' },
              { text: '  architecture  storage-architecture' },
              { text: '  lesson        rls-helper-diff-rule' },
              { text: '  convention    post-migration-smoke-test-required' },
              { text: '' },
              {
                text: '# not one of these contains the words "handle" or "safely"',
                tone: 'muted',
              },
            ]}
          />
          <p className="mt-4 text-label text-ink-muted">
            Run against this project&apos;s own memory, ranked by similarity. Literal keyword
            search returns nothing for that phrasing.
          </p>
        </div>
      </div>
    </Section>
  )
}
