-- ============================================================
-- Tages — pgvector Semantic Search
-- Adds embedding column + vector index alongside pg_trgm.
-- Embeddings are generated by the MCP server or CLI.
-- ============================================================

create extension if not exists "vector";

-- Add embedding column to memories
alter table memories add column embedding vector(1536);

-- HNSW index for fast approximate nearest neighbor
create index memories_embedding_idx
  on memories using hnsw (embedding vector_cosine_ops)
  with (m = 16, ef_construction = 64);

-- RPC: semantic recall using vector similarity
create or replace function semantic_recall(
  p_project_id uuid,
  p_embedding vector(1536),
  p_type text default null,
  p_limit int default 5,
  p_threshold real default 0.7
)
returns table (
  id uuid,
  project_id uuid,
  key text,
  value text,
  type text,
  source text,
  agent_name text,
  file_paths text[],
  tags text[],
  confidence real,
  created_at timestamptz,
  updated_at timestamptz,
  similarity real
) as $$
begin
  return query
    select
      m.id, m.project_id, m.key, m.value, m.type, m.source,
      m.agent_name, m.file_paths, m.tags, m.confidence,
      m.created_at, m.updated_at,
      (1 - (m.embedding <=> p_embedding))::real as similarity
    from memories m
    where m.project_id = p_project_id
      and m.embedding is not null
      and (1 - (m.embedding <=> p_embedding)) > p_threshold
      and (p_type is null or m.type = p_type)
    order by m.embedding <=> p_embedding
    limit p_limit;
end;
$$ language plpgsql security definer stable;

-- RPC: hybrid recall (combine trigram + vector, deduplicate)
create or replace function hybrid_recall(
  p_project_id uuid,
  p_query text,
  p_embedding vector(1536) default null,
  p_type text default null,
  p_limit int default 5
)
returns table (
  id uuid,
  project_id uuid,
  key text,
  value text,
  type text,
  source text,
  file_paths text[],
  tags text[],
  confidence real,
  created_at timestamptz,
  similarity real,
  match_type text
) as $$
begin
  return query
    with trigram_results as (
      select m.id, m.project_id, m.key, m.value, m.type, m.source,
        m.file_paths, m.tags, m.confidence, m.created_at,
        greatest(similarity(m.key, p_query), similarity(m.value, p_query)) as sim,
        'trigram'::text as mtype
      from memories m
      where m.project_id = p_project_id
        and greatest(similarity(m.key, p_query), similarity(m.value, p_query)) > 0.2
        and (p_type is null or m.type = p_type)
    ),
    vector_results as (
      select m.id, m.project_id, m.key, m.value, m.type, m.source,
        m.file_paths, m.tags, m.confidence, m.created_at,
        (1 - (m.embedding <=> p_embedding))::real as sim,
        'semantic'::text as mtype
      from memories m
      where m.project_id = p_project_id
        and p_embedding is not null
        and m.embedding is not null
        and (1 - (m.embedding <=> p_embedding)) > 0.5
        and (p_type is null or m.type = p_type)
    ),
    combined as (
      select * from trigram_results
      union all
      select * from vector_results
    ),
    deduped as (
      select distinct on (id) *
      from combined
      order by id, sim desc
    )
    select id, project_id, key, value, type, source,
      file_paths, tags, confidence, created_at,
      sim as similarity, mtype as match_type
    from deduped
    order by sim desc
    limit p_limit;
end;
$$ language plpgsql security definer stable;
