-- ============================================================
-- Tages — restore recall for service-role callers (regression from 0066)
--
-- SYMPTOM: `tages recall <anything>` returns "No memories found matching ..."
-- for every query, on every project, while `tages recall --all` lists all
-- memories correctly.
--
-- CAUSE: 0066_recall_rls_guards.sql added an `auth.uid()` access guard to all
-- four recall RPCs. All four are SECURITY DEFINER, so the guard is an ordinary
-- predicate rather than RLS, and the service role does NOT bypass it: under
-- TAGES_SERVICE_KEY (the CI/headless path in
-- packages/cli/src/auth/session.ts:15-18) `auth.uid()` is NULL, both branches
-- of the guard evaluate false, and every recall RPC returns zero rows.
--
-- `tages recall --all` keeps working because it is a plain PostgREST
-- `from('memories').select()` (packages/cli/src/commands/recall.ts:220-234),
-- not an RPC — and the service role DOES bypass RLS on the table. That
-- asymmetry is the whole bug: identical credentials, full table read, zero
-- RPC rows.
--
-- 0066's own header called this out ("*** KNOWN BEHAVIOR CHANGE — service-role
-- callers ***") and deliberately deferred it: "adding a `service_role` escape
-- hatch here would deviate from the sanctioned pattern, so it is deliberately
-- NOT done in this migration and is flagged for a separate decision."
-- This migration IS that decision.
--
-- WHY THE EXEMPTION IS NOT A NEW HOLE: a service-role caller can already
-- `select * from memories` for any project with RLS bypassed. Exempting it
-- from the RPC guard therefore grants zero capability it does not already
-- have; it only restores parity between the RPC path and the table path.
-- The hole 0066 actually closed — an AUTHENTICATED non-member reading another
-- project's memories by guessing its UUID — is untouched: that caller's role
-- claim is 'authenticated', never 'service_role', so it still hits the
-- owner/member check and still gets zero rows.
--
-- The role claim is read straight from the request-scoped JWT GUC rather than
-- via `auth.role()`, for two reasons: the GUC is unaffected by SECURITY
-- DEFINER (unlike `current_user`, which becomes the function owner and would
-- silently exempt EVERY caller), and it does not depend on the `auth.role()`
-- helper still existing. The expression is character-for-character the body of
-- Supabase's own `auth.role()`. `nullif(..., '')` guards the empty-string case,
-- since `''::jsonb` would throw; an absent GUC yields NULL, and
-- `NULL is distinct from 'service_role'` is true, so the guard still applies.
-- Fail-closed on every path that is not provably service_role.
--
-- Everything else in all four functions is carried forward from 0066
-- VERBATIM — signatures, RETURNS TABLE column lists, every threshold, CTE,
-- filter and ORDER BY, and `security definer stable set search_path`. This
-- file was generated by textual substitution of the guard block alone, so an
-- authorized caller's row set, scores and ordering are bit-identical to 0066.
--
-- NOTE: this migration fixes the SERVICE-ROLE path only. A signed-in user who
-- is neither the project owner nor an active team member still gets zero rows
-- from recall — correctly. That is a membership/data question, not a code one.
-- ============================================================

set search_path = public, extensions;

-- ------------------------------------------------------------
-- 1. recall_memories — live definition from
--    0061_word_similarity_recall_fix.sql:73-130, reproduced verbatim with
--    only the access guard added before `return query`.
-- ------------------------------------------------------------
create or replace function recall_memories(
  p_project_id uuid,
  p_query text,
  p_type text default null,
  p_limit int default 5
)
returns table (
  id uuid,
  project_id uuid,
  key text,
  value text,
  type text,
  source text,
  agent_name text,
  file_paths text[],
  tags text[],
  confidence real,
  conditions text[],
  phases text[],
  cross_system_refs text[],
  examples jsonb,
  execution_flow jsonb,
  created_at timestamptz,
  updated_at timestamptz,
  similarity real
) as $$
begin
  -- Verify caller has access to the project.
  -- The service role is exempt: it already reads `memories` / `memory_chunks`
  -- directly with RLS bypassed, so this branch grants it nothing new — it only
  -- restores parity between the RPCs and the plain table reads. See 0068 header.
  if coalesce(
       nullif(current_setting('request.jwt.claim.role', true), ''),
       nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'role'
     ) is distinct from 'service_role'
     and not exists (
       select 1 from projects p
       where p.id = p_project_id
         and (p.owner_id = auth.uid() or is_project_member(auth.uid(), p.id))
     ) then
    return;
  end if;

  return query
    select
      m.id, m.project_id, m.key, m.value, m.type, m.source,
      m.agent_name, m.file_paths, m.tags, m.confidence,
      m.conditions, m.phases, m.cross_system_refs,
      m.examples, m.execution_flow,
      m.created_at, m.updated_at,
      greatest(
        similarity(m.key, p_query),
        similarity(m.value, p_query),
        word_similarity(p_query, m.key),
        word_similarity(p_query, m.value)
      ) as similarity
    from memories m
    where m.project_id = p_project_id
      and m.status = 'live'
      and (
        greatest(
          similarity(m.key, p_query),
          similarity(m.value, p_query)
        ) > 0.15
        or m.key ilike '%' || p_query || '%'
        or m.value ilike '%' || p_query || '%'
        or word_similarity(p_query, m.value) > 0.4
        or word_similarity(p_query, m.key) > 0.4
      )
      and (p_type is null or m.type = p_type)
    order by similarity desc
    limit p_limit;
end;
$$ language plpgsql security definer stable set search_path = public, extensions;

-- ------------------------------------------------------------
-- 2. semantic_recall — live definition from
--    0060_temporal_date_anchoring.sql:136-184, reproduced verbatim with
--    only the access guard added before `return query`.
-- ------------------------------------------------------------
create or replace function semantic_recall(
  p_project_id uuid,
  p_embedding vector(1536),
  p_type text default null,
  p_limit int default 5,
  p_threshold real default 0.3
)
returns table (
  id uuid,
  project_id uuid,
  key text,
  value text,
  type text,
  source text,
  agent_name text,
  file_paths text[],
  tags text[],
  confidence real,
  conditions text[],
  phases text[],
  cross_system_refs text[],
  examples jsonb,
  execution_flow jsonb,
  created_at timestamptz,
  updated_at timestamptz,
  referenced_date timestamptz,
  relative_date timestamptz,
  similarity real
) as $$
begin
  -- Verify caller has access to the project.
  -- The service role is exempt: it already reads `memories` / `memory_chunks`
  -- directly with RLS bypassed, so this branch grants it nothing new — it only
  -- restores parity between the RPCs and the plain table reads. See 0068 header.
  if coalesce(
       nullif(current_setting('request.jwt.claim.role', true), ''),
       nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'role'
     ) is distinct from 'service_role'
     and not exists (
       select 1 from projects p
       where p.id = p_project_id
         and (p.owner_id = auth.uid() or is_project_member(auth.uid(), p.id))
     ) then
    return;
  end if;

  return query
    select
      m.id, m.project_id, m.key, m.value, m.type, m.source,
      m.agent_name, m.file_paths, m.tags, m.confidence,
      m.conditions, m.phases, m.cross_system_refs,
      m.examples, m.execution_flow,
      m.created_at, m.updated_at,
      m.referenced_date, m.relative_date,
      (1 - (m.embedding <=> p_embedding))::real as similarity
    from memories m
    where m.project_id = p_project_id
      and m.status = 'live'
      and m.embedding is not null
      and (1 - (m.embedding <=> p_embedding)) > p_threshold
      and (p_type is null or m.type = p_type)
    order by m.embedding <=> p_embedding
    limit p_limit;
end;
$$ language plpgsql security definer stable set search_path = public, extensions;

-- ------------------------------------------------------------
-- 3. hybrid_recall — live definition from
--    0062_hybrid_recall_rrf_fusion.sql:77-177 (the RRF-fusion rewrite, NOT
--    the superseded 0061 UNION ALL / DISTINCT ON version), reproduced
--    verbatim with only the access guard added before `return query`.
--    The guard is a standalone early return: it is deliberately NOT bolted
--    onto trigram_scored/vector_scored as an extra WHERE branch, which
--    would change each leg's candidate set and therefore its RANK() and the
--    fused RRF scores.
-- ------------------------------------------------------------
create or replace function hybrid_recall(
  p_project_id uuid,
  p_query text,
  p_embedding vector(1536) default null,
  p_type text default null,
  p_limit int default 5
)
returns table (
  id uuid,
  project_id uuid,
  key text,
  value text,
  type text,
  source text,
  file_paths text[],
  tags text[],
  confidence real,
  created_at timestamptz,
  referenced_date timestamptz,
  relative_date timestamptz,
  similarity real,
  match_type text
) as $$
begin
  -- Verify caller has access to the project.
  -- The service role is exempt: it already reads `memories` / `memory_chunks`
  -- directly with RLS bypassed, so this branch grants it nothing new — it only
  -- restores parity between the RPCs and the plain table reads. See 0068 header.
  if coalesce(
       nullif(current_setting('request.jwt.claim.role', true), ''),
       nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'role'
     ) is distinct from 'service_role'
     and not exists (
       select 1 from projects p
       where p.id = p_project_id
         and (p.owner_id = auth.uid() or is_project_member(auth.uid(), p.id))
     ) then
    return;
  end if;

  return query
    with trigram_scored as (
      select m.id, m.project_id, m.key, m.value, m.type, m.source,
        m.file_paths, m.tags, m.confidence, m.created_at,
        m.referenced_date, m.relative_date,
        greatest(
          similarity(m.key, p_query),
          similarity(m.value, p_query),
          word_similarity(p_query, m.key),
          word_similarity(p_query, m.value)
        ) as sim
      from memories m
      where m.project_id = p_project_id
        and (
          greatest(similarity(m.key, p_query), similarity(m.value, p_query)) > 0.15
          or word_similarity(p_query, m.value) > 0.4
          or word_similarity(p_query, m.key) > 0.4
        )
        and (p_type is null or m.type = p_type)
    ),
    trigram_results as (
      select *, rank() over (order by sim desc) as trigram_rank
      from trigram_scored
    ),
    vector_scored as (
      select m.id, m.project_id, m.key, m.value, m.type, m.source,
        m.file_paths, m.tags, m.confidence, m.created_at,
        m.referenced_date, m.relative_date,
        (1 - (m.embedding <=> p_embedding))::real as sim
      from memories m
      where m.project_id = p_project_id
        and p_embedding is not null
        and m.embedding is not null
        and (1 - (m.embedding <=> p_embedding)) > 0.3
        and (p_type is null or m.type = p_type)
    ),
    vector_results as (
      select *, rank() over (order by sim desc) as vector_rank
      from vector_scored
    ),
    fused as (
      select
        coalesce(t.id, v.id) as id,
        coalesce(t.project_id, v.project_id) as project_id,
        coalesce(t.key, v.key) as key,
        coalesce(t.value, v.value) as value,
        coalesce(t.type, v.type) as type,
        coalesce(t.source, v.source) as source,
        coalesce(t.file_paths, v.file_paths) as file_paths,
        coalesce(t.tags, v.tags) as tags,
        coalesce(t.confidence, v.confidence) as confidence,
        coalesce(t.created_at, v.created_at) as created_at,
        coalesce(t.referenced_date, v.referenced_date) as referenced_date,
        coalesce(t.relative_date, v.relative_date) as relative_date,
        (
          coalesce(1.0 / (60 + t.trigram_rank), 0)
          + coalesce(1.0 / (60 + v.vector_rank), 0)
        )::real as rrf_score,
        case
          when t.id is not null and v.id is not null then 'both'
          when t.id is not null then 'trigram'
          else 'semantic'
        end as match_type
      from trigram_results t
      full outer join vector_results v on t.id = v.id
    )
    -- Every output column must be table-qualified here: plpgsql's RETURNS
    -- TABLE out-params shadow same-named columns and raise 42702 otherwise.
    select f.id, f.project_id, f.key, f.value, f.type, f.source,
      f.file_paths, f.tags, f.confidence, f.created_at,
      f.referenced_date, f.relative_date,
      f.rrf_score as similarity, f.match_type
    from fused f
    order by f.rrf_score desc
    limit p_limit;
end;
$$ language plpgsql security definer stable set search_path = public, extensions;

-- ------------------------------------------------------------
-- 4. chunk_semantic_recall — live definition from
--    0064_chunk_aware_recall.sql:56-129, reproduced verbatim with only the
--    access guard added before `return query`. Note this RPC reaches
--    `memory_chunks` (0063) as well as `memories`; the guard is on the
--    project, which covers both, since matched_chunks filters
--    `c.project_id = p_project_id`.
-- ------------------------------------------------------------
create or replace function chunk_semantic_recall(
  p_project_id uuid,
  p_embedding vector(1536),
  p_type text default null,
  p_limit int default 5,
  p_threshold real default 0.3
)
returns table (
  id uuid,
  project_id uuid,
  key text,
  value text,
  type text,
  source text,
  agent_name text,
  file_paths text[],
  tags text[],
  confidence real,
  conditions text[],
  phases text[],
  cross_system_refs text[],
  examples jsonb,
  execution_flow jsonb,
  created_at timestamptz,
  updated_at timestamptz,
  referenced_date timestamptz,
  relative_date timestamptz,
  similarity real,
  chunk_index int,
  chunk_text text
) as $$
begin
  -- Verify caller has access to the project.
  -- The service role is exempt: it already reads `memories` / `memory_chunks`
  -- directly with RLS bypassed, so this branch grants it nothing new — it only
  -- restores parity between the RPCs and the plain table reads. See 0068 header.
  if coalesce(
       nullif(current_setting('request.jwt.claim.role', true), ''),
       nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'role'
     ) is distinct from 'service_role'
     and not exists (
       select 1 from projects p
       where p.id = p_project_id
         and (p.owner_id = auth.uid() or is_project_member(auth.uid(), p.id))
     ) then
    return;
  end if;

  return query
    with matched_chunks as (
      select
        c.memory_id,
        c.chunk_index,
        c.chunk_text,
        (1 - (c.embedding <=> p_embedding))::real as sim
      from memory_chunks c
      join memories m on m.id = c.memory_id
      where c.project_id = p_project_id
        and c.embedding is not null
        and m.status = 'live'
        and (p_type is null or m.type = p_type)
        and (1 - (c.embedding <=> p_embedding)) > p_threshold
    ),
    winning_chunks as (
      -- One row per memory: its best-matching chunk. DISTINCT ON's
      -- leading ORDER BY column must be memory_id — the cross-memory
      -- ORDER BY sim DESC happens in the outer query below, not here.
      -- Columns table-qualified: plpgsql's RETURNS TABLE out-params
      -- (chunk_index, chunk_text) shadow same-named columns and raise
      -- 42702 if referenced unqualified.
      select distinct on (mc.memory_id)
        mc.memory_id, mc.chunk_index, mc.chunk_text, mc.sim
      from matched_chunks mc
      order by mc.memory_id, mc.sim desc
    )
    select
      m.id, m.project_id, m.key, m.value, m.type, m.source,
      m.agent_name, m.file_paths, m.tags, m.confidence,
      m.conditions, m.phases, m.cross_system_refs,
      m.examples, m.execution_flow,
      m.created_at, m.updated_at,
      m.referenced_date, m.relative_date,
      wc.sim as similarity,
      wc.chunk_index, wc.chunk_text
    from winning_chunks wc
    join memories m on m.id = wc.memory_id
    order by wc.sim desc
    limit p_limit;
end;
$$ language plpgsql security definer stable set search_path = public, extensions;


-- ============================================================
-- Verification (see the automated harness this fix shipped with):
--
-- 1. Signature/shape drift check — all four must be unchanged vs 0066:
--      select p.proname, pg_get_function_identity_arguments(p.oid) as args,
--             pg_get_function_result(p.oid) as result,
--             p.prosecdef, p.provolatile, p.proconfig
--      from pg_proc p join pg_namespace n on n.oid = p.pronamespace
--      where n.nspname = 'public'
--        and p.proname in ('recall_memories','semantic_recall',
--                          'hybrid_recall','chunk_semantic_recall');
--
-- 2. The three-caller matrix, against a project with >= 1 matching live
--    memory. Set the JWT claim, then call:
--      set request.jwt.claims = '{"role":"service_role"}';
--        -> MUST return rows   (0066: returned 0 — this is the regression)
--      set request.jwt.claims = '{"role":"authenticated","sub":"<owner uuid>"}';
--        -> MUST return the same rows as under 0066 (no change)
--      set request.jwt.claims = '{"role":"authenticated","sub":"<outsider>"}';
--        -> MUST return 0 rows (0066's fix must survive)
--
-- 3. End to end, with TAGES_SERVICE_KEY exported:
--      tages recall "shadow"   -> returns no-accent-tinted-shadows
-- ============================================================
