-- ============================================================
-- Tages — hybrid_recall must return only live memories
--
-- `recall_memories`, `semantic_recall` and `chunk_semantic_recall` all filter
-- `m.status = 'live'`. `hybrid_recall` never has. `memories.status` is one of
-- ('live','pending','archived') per 0054, where `pending` is the `observe`
-- staging queue awaiting human approval and `archived` is a soft delete.
--
-- So the hybrid path — the default for `tages recall`, and the one the MCP
-- `recall` tool uses — has been surfacing memories the user explicitly did not
-- approve, and memories they explicitly forgot. `remoteHybridRecall` in
-- supabase-sync.ts maps rows straight through with no client-side filter, so
-- nothing downstream compensates.
--
-- Carried forward unchanged from 0062 through 0066 and 0068, each of which
-- recreated the function. This adds the filter to both legs of the fusion.
--
-- The function body is otherwise byte-identical to 0068: this file was
-- generated by extracting 0068's hybrid_recall and inserting the two
-- predicates, so the guard, the RRF scoring, the ranks and the ordering cannot
-- have drifted. Adding the filter inside each leg (rather than around the
-- fused result) is deliberate: RANK() is computed per leg, so filtering after
-- fusion would leave ranks that had been computed over rows the caller may not
-- see, changing the scores of the rows they may.
-- ============================================================

set search_path = public, extensions;

create or replace function hybrid_recall(
  p_project_id uuid,
  p_query text,
  p_embedding vector(1536) default null,
  p_type text default null,
  p_limit int default 5
)
returns table (
  id uuid,
  project_id uuid,
  key text,
  value text,
  type text,
  source text,
  file_paths text[],
  tags text[],
  confidence real,
  created_at timestamptz,
  referenced_date timestamptz,
  relative_date timestamptz,
  similarity real,
  match_type text
) as $$
begin
  -- Verify caller has access to the project.
  -- The service role is exempt: it already reads `memories` / `memory_chunks`
  -- directly with RLS bypassed, so this branch grants it nothing new — it only
  -- restores parity between the RPCs and the plain table reads. See 0068 header.
  if coalesce(
       nullif(current_setting('request.jwt.claim.role', true), ''),
       nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'role'
     ) is distinct from 'service_role'
     and not exists (
       select 1 from projects p
       where p.id = p_project_id
         and (p.owner_id = auth.uid() or is_project_member(auth.uid(), p.id))
     ) then
    return;
  end if;

  return query
    with trigram_scored as (
      select m.id, m.project_id, m.key, m.value, m.type, m.source,
        m.file_paths, m.tags, m.confidence, m.created_at,
        m.referenced_date, m.relative_date,
        greatest(
          similarity(m.key, p_query),
          similarity(m.value, p_query),
          word_similarity(p_query, m.key),
          word_similarity(p_query, m.value)
        ) as sim
      from memories m
      where m.project_id = p_project_id
        and m.status = 'live'
        and (
          greatest(similarity(m.key, p_query), similarity(m.value, p_query)) > 0.15
          or word_similarity(p_query, m.value) > 0.4
          or word_similarity(p_query, m.key) > 0.4
        )
        and (p_type is null or m.type = p_type)
    ),
    trigram_results as (
      select *, rank() over (order by sim desc) as trigram_rank
      from trigram_scored
    ),
    vector_scored as (
      select m.id, m.project_id, m.key, m.value, m.type, m.source,
        m.file_paths, m.tags, m.confidence, m.created_at,
        m.referenced_date, m.relative_date,
        (1 - (m.embedding <=> p_embedding))::real as sim
      from memories m
      where m.project_id = p_project_id
        and m.status = 'live'
        and p_embedding is not null
        and m.embedding is not null
        and (1 - (m.embedding <=> p_embedding)) > 0.3
        and (p_type is null or m.type = p_type)
    ),
    vector_results as (
      select *, rank() over (order by sim desc) as vector_rank
      from vector_scored
    ),
    fused as (
      select
        coalesce(t.id, v.id) as id,
        coalesce(t.project_id, v.project_id) as project_id,
        coalesce(t.key, v.key) as key,
        coalesce(t.value, v.value) as value,
        coalesce(t.type, v.type) as type,
        coalesce(t.source, v.source) as source,
        coalesce(t.file_paths, v.file_paths) as file_paths,
        coalesce(t.tags, v.tags) as tags,
        coalesce(t.confidence, v.confidence) as confidence,
        coalesce(t.created_at, v.created_at) as created_at,
        coalesce(t.referenced_date, v.referenced_date) as referenced_date,
        coalesce(t.relative_date, v.relative_date) as relative_date,
        (
          coalesce(1.0 / (60 + t.trigram_rank), 0)
          + coalesce(1.0 / (60 + v.vector_rank), 0)
        )::real as rrf_score,
        case
          when t.id is not null and v.id is not null then 'both'
          when t.id is not null then 'trigram'
          else 'semantic'
        end as match_type
      from trigram_results t
      full outer join vector_results v on t.id = v.id
    )
    -- Every output column must be table-qualified here: plpgsql's RETURNS
    -- TABLE out-params shadow same-named columns and raise 42702 otherwise.
    select f.id, f.project_id, f.key, f.value, f.type, f.source,
      f.file_paths, f.tags, f.confidence, f.created_at,
      f.referenced_date, f.relative_date,
      f.rrf_score as similarity, f.match_type
    from fused f
    order by f.rrf_score desc
    limit p_limit;
end;
$$ language plpgsql security definer stable set search_path = public, extensions;
